### ISSUE TITLE
JSON files describing products for each set

### ISSUE THREAD

**Issue by aaronaskew** [augenblick/CardShop#10]
Tasks

- [x] Premiere
- [x] A New Hope
- [x] Hoth
- [x] Dagobah
- [x] Cloud City
- [x] Jabba's Palace
- [x] Special Edition
- [x] Endor
- [x] Death Star II
  - XR - do not include in rarity_map as they were not available in booster packs
- [x] Tatooine
  - [x] Change rarity codes (R8, R9) 
- [x] Coruscant
- [x] Theed Palace
  - For Coruscant and Theed Palace, assume 1/3 U/C ratio. 

Resources

- https://res.starwarsccg.org/Resources/Star_Wars_CCG_Collecting_Encyclopedia_3.1.pdf

**Comment by aaronaskew** [comment]
@augenblick need to have a meeting regarding Death Star II rarity codes. Still don't quite get how I should handle.

**Comment by aaronaskew** [comment]
@augenblick look closely at Tatooine JSON with regards to commons & uncommons sharing a rarity pool in the pack and look at the chonk regarding rares.

**Comment by aaronaskew** [comment]
@augenblick Need to meet regarding Coruscant as well. Commons and Uncommons share rarity with packs, but the ratios of C/U printing isn't listed in chonk.

Same for Theed Palace

**Comment by aaronaskew** [comment]
@augenblick Premiere Introductory Two-Player Game, 2pp.json only lists 6 cards and is incomplete.

**Comment by augenblick** [comment]
@aaronaskew: regarding the intro 2 player game-- it's only got 6 unique cards (the rest of the box contents are from the standard premiere set).

Anyway, it's got cycle_code == 'premium', so we don't have to worry about it for the MVP.

**Comment by augenblick** [comment]
@aaronaskew Yeah we'll have to discuss Coruscant.  In the meantime I don't know if this bit form an older .pdf helps (haven't looked closely).

![image](https://github.com/augenblick/CardShop/assets/5961531/cd4d5c53-c680-4f34-8790-6fb3bed98946)

**Comment by augenblick** [comment]
> @aaronaskew: regarding the intro 2 player game-- it's only got 6 unique cards (the rest of the box contents are from the standard premiere set).
> 
> Anyway, it's got cycle_code == 'premium', so we don't have to worry about it for the MVP.

@aaronaskew I'm a dummy-- I forgot we talked about including this one specifically.  We'll have to look at how to best set this up.
