### ISSUE TITLE
Store Purchasing

### ISSUE THREAD

**Issue by aaronaskew** [augenblick/CardShop#13]
- [x] Create API endpoint
  - POST, takes JSON based on Request Schema, user_id, list of ~~inventory ids~~ Product Codes and counts
  - Returns list of purchased items if successful or populates an error field in returned JSON if error
- [x] Include total price and updated balance in returned data

**Comment by aaronaskew** [comment]
@augenblick if this is done, please check off tasks and close.

**Comment by augenblick** [comment]
Requirements met
