### ISSUE TITLE
User Authentication (v1)

### ISSUE THREAD

**Issue by aaronaskew** [augenblick/CardShop#17]

**Comment by augenblick** [comment]
**Resources:**
- https://www.c-sharpcorner.com/article/implementing-jwt-refresh-tokens-in-net-8-0/
- https://markjames.dev/blog/jwt-authorization-asp-net-core
- https://jasonwatmore.com/post/2022/01/19/net-6-create-and-validate-jwt-tokens-use-custom-jwt-middleware (.NET 6)
- https://jwt.io/introduction
