### ISSUE TITLE
Codify Backend MVP

### ISSUE THREAD

**Issue by aaronaskew** [augenblick/CardShop#8]

**Comment by aaronaskew** [comment]
Features

Create account
Login
Logout

See shop inventory
Buy from shop
 no economy
View inventory


**products**
booster packs
booster boxes 
2player starter set
from the core set

**Comment by augenblick** [comment]
### MVP Product List:

 - "Limited" variant booster boxes and booster packs for the following sets (support for Foil and Alternate Image cards TBD)
   - Premiere
   - A New Hope
   - Hoth
   - Dagobah
   - Cloud City
   - Jabba's Palace
   - Special Edition
   - Endor
   - Death Star II
   - Tatooine
   - Coruscant
   - Theed Palace

 - Premiere Introductory Two-Player Game (limited variant)
